### ISSUE TITLE
Possible cast error

### ISSUE THREAD

**Issue by akochetova** [knp84/reposit_1#1]
https://github.com/knp84/reposit_1/blob/05ceac5db794b2a21398159147a25dc5ba3da7ac/Project.py#L11

Если пользователь вводит что-то кроме числа, не возникает ли исключение? не следует обрабатывать с помощью try/except

**Comment by knp84** [comment]
вижу

**Comment by akochetova** [comment]
когда вы внесете изменение, откройте pull request и добавьте меня в качестве reviewer, чтобы я мог оставлять комментарии.
